#!/bin/sh

set -e

if [ "$#" -ne 2 ]; then
    echo $0 "<input-log> <log-drive>"
    exit 1
fi

tmpdir=$(mktemp -d -t creepts-XXXXXXXXXX)
(cp $1 /$tmpdir/log.json; cd $tmpdir; brotli log.json; touch -t 200001010000 log.json.br; echo log.json.br | cpio -o -H newc -F log.json.cpio)
cp $tmpdir/log.json.cpio $2

rm -rf $tmpdir
