name: OpenAPI Validation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Speccy
      run: npm i -g speccy
    - name: Validate spec
      run: speccy lint reference/anuto/openapi.yaml
