name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - run: pip install -r requirements.txt
      - run: python -m unittest discover creepts/tests
  
  build:
    runs-on: ubuntu-18.04
    needs: test
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build . -t cartesi/creepts-backend:${TAG}

      - run: echo "::set-env name=TAG::${GITHUB_REF:11}"
        if: startsWith(github.ref, 'refs/tags/v')
  
      - name: Push to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push cartesi/creepts-backend:${TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
