name: Docker
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build . -t 510455014572.dkr.ecr.us-east-1.amazonaws.com/anuto-server:develop-${GITHUB_SHA:0:8}

      - name: Login to AWS ECR
        run: $(aws ecr get-login --no-include-email --region us-east-1)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Push to AWS ECR
        run: docker push 510455014572.dkr.ecr.us-east-1.amazonaws.com/anuto-server:develop-${GITHUB_SHA:0:8}

      - name: Tag GitHub Registry
        run: docker tag 510455014572.dkr.ecr.us-east-1.amazonaws.com/anuto-server:develop-${GITHUB_SHA:0:8} docker.pkg.github.com/cartesi-corp/anuto-server/anuto-server:develop-${GITHUB_SHA:0:8}

      - name: Login to GitHub Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}

      - name: Push to GitHub Registry
        run: docker push docker.pkg.github.com/cartesi-corp/anuto-server/anuto-server:develop-${GITHUB_SHA:0:8}

#      - name: Update staging environment
#        run: aws cloudformation deploy --stack-name staging --template-file ${TEMPLATE_PATH} --parameter-overrides ParameterKey=AnutoServerImageTag,ParameterValue=develop-${GITHUB_SHA:0:8}
#        env:
#          TEMPLATE_PATH: https://cf-templates-1tsksmh05a2pc-us-east-1.s3.amazonaws.com/node.yaml
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
